{{- if .Values.topics.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-creator
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: create-topics
        image: {{ .Values.kafka.image }}
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Waiting Kafka..."
            until /opt/bitnami/kafka/bin/kafka-topics.sh \
                --bootstrap-server kafka:9092 \
                --list > /dev/null 2>&1; do
                echo "Kafka not available, waiting 5 seconds..."
                sleep 5
            done
            echo "Kafka available, going to create topic..."
            while read line; do
              /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists $line \
                --bootstrap-server kafka:9092;
            done < /topics/topics.txt
        volumeMounts:
        - name: topics
          mountPath: /topics
      volumes:
      - name: topics
        configMap:
          name: {{ .Values.topics.configMapName }}
{{- end }}

