apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ems6d-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.ems6d.storageSize }}
