apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trapd-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.trapd.storageSize }}
