{{- if .Values.topics.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-creator
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: create-topics
        image: {{ .Values.kafka.image }}
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Aspetto Kafka..."
            until nc -z kafka.{{ .Values.namespace }}.svc.cluster.local {{ .Values.kafka.port }}; do sleep 2; done
            echo "Kafka disponibile, creo i topic..."
            while read line; do
              /opt/kafka/bin/kafka-topics.sh --create --if-not-exists $line \
                --bootstrap-server kafka.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.kafka.port }};
            done < /topics/topics.txt
        volumeMounts:
        - name: topics
          mountPath: /topics
      volumes:
      - name: topics
        configMap:
          name: {{ .Values.topics.configMapName }}
{{- end }}

