apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tomcat-app-route
spec:
  to:
    kind: Service
    name: {{ .Values.app.name }}
  port:
    targetPort: tcp
  tls:
    termination: passthrough