apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webs-pvc
spec:
  accessModes:
    {{- toYaml .Values.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  {{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
  {{- end }}
